-- MySQL dump 10.13  Distrib 8.0.44, for Win64 (x86_64)
--
-- Host: 127.0.0.1    Database: vcktsassist
-- ------------------------------------------------------
-- Server version	8.0.44

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `questions`
--

DROP TABLE IF EXISTS questions;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE questions (
  questionBankID int NOT NULL,
  questionID int NOT NULL AUTO_INCREMENT,
  questionBody varchar(200) NOT NULL,
  questionGrade varchar(100) NOT NULL,
  questionPhoto varchar(200) DEFAULT NULL,
  questionUnit varchar(100) NOT NULL,
  questionOption1 varchar(100) DEFAULT NULL,
  questionOption2 varchar(100) DEFAULT NULL,
  questionOption3 varchar(100) DEFAULT NULL,
  questionOption4 varchar(100) DEFAULT NULL,
  questionMarks int NOT NULL,
  questionUsed tinyint(1) DEFAULT '0',
  isTrueFalse tinyint(1) DEFAULT '0',
  PRIMARY KEY (questionID),
  UNIQUE KEY questionBody (questionBody),
  KEY questionBankID (questionBankID),
  CONSTRAINT questions_ibfk_1 FOREIGN KEY (questionBankID) REFERENCES questionbanks (questionBankID)
) ENGINE=InnoDB AUTO_INCREMENT=399 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `questions`
--

/*!40000 ALTER TABLE questions DISABLE KEYS */;
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (1,29,'Which statement best describes a key concept in Software Engineering Unit 1?','A',NULL,'1','Explanation related to Unit 1 concept A','Explanation related to Unit 1 concept B','Explanation related to Unit 1 concept C','Explanation related to Unit 1 concept D',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (1,30,'Which statement best describes a key concept in Software Engineering Unit 2?','B',NULL,'2','Explanation related to Unit 2 concept A','Explanation related to Unit 2 concept B','Explanation related to Unit 2 concept C','Explanation related to Unit 2 concept D',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (1,31,'Which statement best describes a key concept in Software Engineering Unit 3?','C',NULL,'3','Explanation related to Unit 3 concept A','Explanation related to Unit 3 concept B','Explanation related to Unit 3 concept C','Explanation related to Unit 3 concept D',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (1,32,'Which statement best describes a key concept in Software Engineering Unit 4?','A',NULL,'4','Explanation related to Unit 4 concept A','Explanation related to Unit 4 concept B','Explanation related to Unit 4 concept C','Explanation related to Unit 4 concept D',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (1,33,'Which statement best describes a key concept in Software Engineering Unit 5?','B',NULL,'5','Explanation related to Unit 5 concept A','Explanation related to Unit 5 concept B','Explanation related to Unit 5 concept C','Explanation related to Unit 5 concept D',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (1,129,'What is the primary concept related to introduction to software engineering in software engineering?','A',NULL,'1','Concept A of Introduction to Software Engineering','Concept B of Introduction to Software Engineering','Concept C of Introduction to Software Engineering','Concept D of Introduction to Software Engineering',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (1,130,'What is the primary concept related to software development life cycle in software engineering?','B',NULL,'2','Concept A of Software Development Life Cycle','Concept B of Software Development Life Cycle','Concept C of Software Development Life Cycle','Concept D of Software Development Life Cycle',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (1,131,'What is the primary concept related to requirements engineering in software engineering?','C',NULL,'3','Concept A of Requirements Engineering','Concept B of Requirements Engineering','Concept C of Requirements Engineering','Concept D of Requirements Engineering',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (1,132,'What is the primary concept related to software design in software engineering?','A',NULL,'3','Concept A of Software Design','Concept B of Software Design','Concept C of Software Design','Concept D of Software Design',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (1,133,'What is the primary concept related to software testing in software engineering?','B',NULL,'5','Concept A of Software Testing','Concept B of Software Testing','Concept C of Software Testing','Concept D of Software Testing',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (1,134,'What is the primary concept related to software maintenance in software engineering?','C',NULL,'4','Concept A of Software Maintenance','Concept B of Software Maintenance','Concept C of Software Maintenance','Concept D of Software Maintenance',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (1,135,'What is the primary concept related to agile and modern practices in software engineering?','A',NULL,'6','Concept A of Agile and Modern Practices','Concept B of Agile and Modern Practices','Concept C of Agile and Modern Practices','Concept D of Agile and Modern Practices',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (1,136,'What is the primary concept related to project management in software engineering?','B',NULL,'7','Concept A of Project Management','Concept B of Project Management','Concept C of Project Management','Concept D of Project Management',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,229,'ITcomplex1','C',NULL,'1','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,230,'ITcomplex2','C',NULL,'2','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,231,'ITcomplex3','C',NULL,'3','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,232,'ITcomplex4','C',NULL,'1','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,233,'ITcomplex5','C',NULL,'2','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,234,'ITcomplex6','C',NULL,'3','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,235,'ITcomplex7','C',NULL,'1','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,236,'ITcomplex8','C',NULL,'2','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,237,'ITcomplex9','C',NULL,'3','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,238,'ITcomplex10','C',NULL,'1','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,239,'ITmedium1','B',NULL,'2','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,240,'ITmedium2','B',NULL,'3','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,241,'ITmedium3','B',NULL,'1','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,242,'ITmedium4','B',NULL,'2','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,243,'ITmedium5','B',NULL,'3','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,244,'ITmedium6','B',NULL,'1','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,245,'ITmedium7','B',NULL,'2','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,246,'ITmedium8','B',NULL,'3','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,247,'ITmedium9','B',NULL,'1','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,248,'ITmedium10','B',NULL,'2','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,249,'ITeasy1','A',NULL,'3','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,250,'ITeasy2','A',NULL,'1','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,251,'ITeasy3','A',NULL,'2','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,252,'ITeasy4','A',NULL,'3','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,253,'ITeasy5','A',NULL,'1','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,254,'ITeasy6','A',NULL,'2','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,255,'ITeasy7','A',NULL,'3','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,256,'ITeasy8','A',NULL,'1','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,257,'ITeasy9','A',NULL,'2','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (9,258,'ITeasy10','A',NULL,'3','option1','option2','option3','option4',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,259,'ITlaqcomplex1','C',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,260,'ITlaqcomplex2','C',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,261,'ITlaqcomplex3','C',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,262,'ITlaqcomplex4','C',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,263,'ITlaqcomplex5','C',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,264,'ITlaqcomplex6','C',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,265,'ITlaqcomplex7','C',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,266,'ITlaqcomplex8','C',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,267,'ITlaqcomplex9','C',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,268,'ITlaqcomplex10','C',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,269,'ITlaqmedium1','B',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,270,'ITlaqmedium2','B',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,271,'ITlaqmedium3','B',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,272,'ITlaqmedium4','B',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,273,'ITlaqmedium5','B',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,274,'ITlaqmedium6','B',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,275,'ITlaqmedium7','B',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,276,'ITlaqmedium8','B',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,277,'ITlaqmedium9','B',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,278,'ITlaqmedium10','B',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,279,'ITlaqeasy1','A',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,280,'ITlaqeasy2','A',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,281,'ITlaqeasy3','A',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,282,'ITlaqeasy4','A',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,283,'ITlaqeasy5','A',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,284,'ITlaqeasy6','A',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,285,'ITlaqeasy7','A',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,286,'ITlaqeasy8','A',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,287,'ITlaqeasy9','A',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (10,288,'ITlaqeasy10','A',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,289,'ITsaqcomplex1','C',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,290,'ITsaqcomplex2','C',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,291,'ITsaqcomplex3','C',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,292,'ITsaqcomplex4','C',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,293,'ITsaqcomplex5','C',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,294,'ITsaqcomplex6','C',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,295,'ITsaqcomplex7','C',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,296,'ITsaqcomplex8','C',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,297,'ITsaqcomplex9','C',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,298,'ITsaqcomplex10','C',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,299,'ITsaqmedium1','B',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,300,'ITsaqmedium2','B',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,301,'ITsaqmedium3','B',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,302,'ITsaqmedium4','B',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,303,'ITsaqmedium5','B',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,304,'ITsaqmedium6','B',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,305,'ITsaqmedium7','B',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,306,'ITsaqmedium8','B',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,307,'ITsaqmedium9','B',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,308,'ITsaqmedium10','B',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,309,'ITsaqeasy1','A',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,310,'ITsaqeasy2','A',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,311,'ITsaqeasy3','A',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,312,'ITsaqeasy4','A',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,313,'ITsaqeasy5','A',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,314,'ITsaqeasy6','A',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,315,'ITsaqeasy7','A',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,316,'ITsaqeasy8','A',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,317,'ITsaqeasy9','A',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (11,318,'ITsaqeasy10','A',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,319,'Which interface is the root of the Java Collections Framework?','A',NULL,'3','Collection','Iterable','List','Map',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,320,'Which collection allows duplicate elements?','A',NULL,'3','Set','List','Map','Queue',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,321,'Which class maintains elements in sorted order?','A',NULL,'3','HashSet','TreeSet','LinkedHashSet','Vector',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,322,'Which collection guarantees insertion order?','A',NULL,'3','HashSet','TreeSet','LinkedHashSet','PriorityQueue',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,323,'Which map implementation allows null keys and values?','B',NULL,'3','HashMap','TreeMap','Hashtable','ConcurrentHashMap',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,324,'Which collection is synchronized by default?','B',NULL,'3','ArrayList','HashMap','Vector','HashSet',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,325,'Which interface does Queue extend?','A',NULL,'3','Collection','List','Set','Map',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,326,'Which method removes all elements from a collection?','A',NULL,'3','clear()','removeAll()','delete()','empty()',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,327,'Which class implements a resizable array?','A',NULL,'3','ArrayList','Vector','LinkedList','Stack',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,328,'Which collection is best for LIFO operations?','A',NULL,'3','Queue','Stack','Deque','PriorityQueue',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,329,'Which collection is best for FIFO operations?','A',NULL,'3','Stack','Queue','Deque','Vector',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,330,'Which map maintains insertion order?','B',NULL,'3','HashMap','TreeMap','LinkedHashMap','ConcurrentHashMap',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,331,'Which collection does not allow duplicate keys?','B',NULL,'3','List','Set','Map','Queue',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,332,'Which collection is backed by a hash table?','B',NULL,'3','HashSet','TreeSet','LinkedList','ArrayList',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,333,'Which collection allows fast lookup by key?','A',NULL,'3','List','Set','Map','Queue',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,334,'Which collection is best for priority-based ordering?','B',NULL,'3','Stack','Queue','PriorityQueue','Deque',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,335,'Which method checks if a collection is empty?','A',NULL,'3','isEmpty()','size()','empty()','clear()',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,336,'Which collection is fail-fast during iteration?','C',NULL,'3','HashMap','ConcurrentHashMap','Vector','Hashtable',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,337,'Which collection is fail-safe during iteration?','C',NULL,'3','HashMap','ConcurrentHashMap','ArrayList','TreeSet',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (6,338,'Which collection is best for implementing a double-ended queue?','B',NULL,'3','Stack','Queue','Deque','PriorityQueue',1,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,339,'Explain the lifecycle of a servlet with suitable methods.','A',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,340,'Differentiate between HashMap and Hashtable in Java.','B',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,341,'What is JDBC? Describe the different types of JDBC drivers.','C',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,342,'Explain the difference between doGet() and doPost() methods in servlets.','B',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,343,'What is RMI in Java? How does it differ from socket programming?','A',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,344,'Explain the role of PreparedStatement in JDBC. Why is it preferred over Statement?','C',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,345,'What is the difference between ArrayList and LinkedList?','A',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,346,'Explain the concept of session management in servlets.','B',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,347,'What is the difference between Comparable and Comparator interfaces?','C',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,348,'Explain the working of TreeSet and how it maintains order.','B',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,349,'What is the purpose of synchronized collections? Give examples.','A',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,350,'Explain the difference between forward() and sendRedirect() in servlets.','C',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,351,'What is the difference between Vector and ArrayList?','B',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,352,'Explain the concept of fail-fast and fail-safe iterators with examples.','A',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,353,'What is the difference between ServletContext and ServletConfig?','C',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,354,'Explain the difference between HashSet and LinkedHashSet.','B',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,355,'What is the role of CallableStatement in JDBC?','A',NULL,'3',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,356,'Explain the difference between stateless and stateful session beans in EJB.','C',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,357,'What is the difference between JSP directives and JSP actions?','B',NULL,'1',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (7,358,'Explain the difference between checked and unchecked exceptions in Java.','A',NULL,'2',NULL,NULL,NULL,NULL,4,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,379,'Explain the complete lifecycle of a servlet with a neat diagram. Discuss the role of init(), service(), and destroy() methods.','B',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,380,'Differentiate between HashMap, Hashtable, and ConcurrentHashMap. Explain their thread-safety, null handling, and performance characteristics.','C',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,381,'Describe the architecture of JDBC. Explain the four types of JDBC drivers with advantages and disadvantages.','A',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,382,'Discuss session management techniques in servlets. Compare cookies, URL rewriting, and HttpSession with examples.','B',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,383,'Explain Remote Method Invocation (RMI) in Java. Describe the steps involved in creating and invoking a remote object.','A',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,384,'What is the difference between PreparedStatement and CallableStatement in JDBC? Explain with examples of parameter binding and stored procedure calls.','C',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,385,'Discuss the differences between ArrayList, LinkedList, and Vector. Explain their internal implementations and use cases.','B',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,386,'Explain the concept of fail-fast and fail-safe iterators in Java Collections. Provide examples of collections that exhibit each behavior.','A',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,387,'Describe the differences between ServletContext and ServletConfig. Explain their roles with suitable examples.','C',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,388,'Explain the working of JSP lifecycle. Discuss translation, compilation, initialization, execution, and cleanup phases.','B',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,389,'Discuss the differences between stateless and stateful session beans in EJB. Explain scenarios where each is preferred.','A',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,390,'Explain the difference between Comparable and Comparator interfaces. Provide code examples to illustrate sorting using both.','C',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,391,'Describe the architecture of Java Message Service (JMS). Explain point-to-point and publish-subscribe models with examples.','B',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,392,'Explain the difference between forward() and sendRedirect() in servlets. Discuss their impact on request/response objects.','A',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,393,'Discuss the role of TreeSet and TreeMap in maintaining sorted collections. Explain how they use Comparable and Comparator.','C',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,394,'Explain the difference between checked and unchecked exceptions in Java. Provide examples and discuss best practices for exception handling.','B',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,395,'Describe the working of PriorityQueue in Java. Explain how elements are ordered and give a practical use case.','A',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,396,'Explain the architecture of Hibernate. Discuss how it simplifies database interaction compared to JDBC.','C',NULL,'3',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,397,'Discuss the role of filters in servlets. Explain how they can be used for logging, authentication, and request modification.','B',NULL,'2',NULL,NULL,NULL,NULL,8,0,0);
INSERT INTO questions (questionBankID, questionID, questionBody, questionGrade, questionPhoto, questionUnit, questionOption1, questionOption2, questionOption3, questionOption4, questionMarks, questionUsed, isTrueFalse) VALUES (12,398,'Explain the difference between JSP directives (<%@ %>) and JSP actions (<jsp:...>).','A',NULL,'1',NULL,NULL,NULL,NULL,8,0,0);
/*!40000 ALTER TABLE questions ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed
